### ISSUE TITLE
[feat] Project 구조 설계

### ISSUE THREAD

**Issue by kldaji** [kldaji/roulette#1]
## EPIC
- 모든 화면

## STORY
- 화면 간 이동을 구현합니다.

## TASK
- [x] 사용할 Fragment 생성
- [x] Navigation Graph 생성하여 Fragment 추가 및 이동 경로 설정
- [x] Fragment Container 생성 및 Navigation Graph와 연결
