### ISSUE TITLE
[feat] 룰렛 뷰 생성

### ISSUE THREAD

**Issue by kldaji** [kldaji/roulette#2]
## EPIC
- 룰렛 화면

## STORY
- 룰렛을 생성합니다.

## TASK

- [x] 룰렛 테두리 그리기 (ProgressBar)
- [x] Partition Dummy Data 생성
- [x] Partition 그리기
- [x] 룰렛의 결과를 가리키는 핀 그리기
