### ISSUE TITLE
[feat] 룰렛 결과

### ISSUE THREAD

**Issue by kldaji** [kldaji/roulette#4]
## EPIC
- 룰렛 화면

## STORY
- 룰렛 애니메이션이 종료되면 룰렛 결과를 보여줍니다.

## TASK
- [x] 룰렛 애니메이션 리스너 등록
- [x] 룰렛 결과 로직 구현
- [ ] 룰렛 결과 UI 구현
