### ISSUE TITLE
[feat] 룰렛 게이지

### ISSUE THREAD

**Issue by kldaji** [kldaji/roulette#5]
## EPIC
- 룰렛 화면

## STORY
- 시작 버튼을 꾸욱 누르면 게이지가 올라갑니다.

## TASK
- [x] 시작 버튼 눌렀을 때 게이지 증가 로직 구현
- [x] 시작 버튼 땠을 때 게이지 감소 로직 구현
- [x] 게이지 감소와 애니메이션 종료 시점 맞추기
